### ISSUE TITLE
Similar workflow to copilot.lua

### ISSUE THREAD

**Issue by azdanov** [giuxtaposition/blink-cmp-copilot#5]
Hey. It's not an issue, but I'm not sure where to ask about it.

I was wondering if there is some way to retain similar workflow as in the copilot.lua plugin, where I can have same keybindins, but they change the cmp result:

```
      next = "<M-]>",
      prev = "<M-[>",
      dismiss = "<C-]>",
```

I'm experimenting and trying to figure out which way is better. Either pure copilot.lua or pure blink-cmp-copilot.

My main problem with copilot.lua is that it's a separate plugin with it's own visuals (I like how blink cmp shows the code snippets) yet there is full control of forcing a copilot generated suggestion. But with blink-cmp I loose the ability to generate several different suggestions or dismissing them and often times there is no copilot suggestion at all and I can't seem to trigger it.

Some insights would be most welcome :slightly_smiling_face:

**Comment by giuxtaposition** [comment]
Hello, I don't think your ideal workflow is possible with blink-cmp :thinking: 
As a source provider we do not have control over when blink shows the completions, right now when blink asks for them we send them and that's it

**Comment by azdanov** [comment]
Thanks for answering. I guess not much can be done.
