### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by MrZLeo** [giuxtaposition/blink-cmp-copilot#6]
It seems like adding copilot source will make blink.nvim pop out significant slower than before. Can we do something like async startup and add copilot entry into pop menu when copilot source is enabled? So blink.nvim's pop menu can appear as soon as possible.

**Comment by mathjiajia** [comment]
agree.
didn't see any change even if set `async = true`

**Comment by giuxtaposition** [comment]
Hello,
@MrZLeo, `async = true` is exactly the behaviour you have described.
It was added on https://github.com/Saghen/blink.cmp/commit/533608f56b912aba98250a3c1501ee687d7cf5eb which has not been released yet, sorry for the confusion 😅.

**Comment by MrZLeo** [comment]
> Hello, @MrZLeo, `async = true` is exactly the behaviour you have described. It was added on [Saghen/blink.cmp@533608f](https://github.com/Saghen/blink.cmp/commit/533608f56b912aba98250a3c1501ee687d7cf5eb) which has not been released yet, sorry for the confusion 😅.

Oh I understand, I will try beta version blink. Think you!!! : )
